apiVersion: v1
kind: Namespace
metadata:
  name: project-plato
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project-plato
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: busybox:1.32.0
        command: ['sh', '-c', 'tail -f /dev/null']
        imagePullPolicy: IfNotPresent
        name: busybox
      restartPolicy: Always
